---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/artigos":
    get:
      summary: list artigos
      tags:
      - Artigos
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
    post:
      summary: create artigo
      tags:
      - Artigos
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              example:
                id: 1
                titulo: Repudiandae voluptas est. Nesciunt sunt et. Necessitatibus
                  dolore quibusdam.
                texto: |-
                  Omnis inventore sed. Nostrum ex laborum. Enim eligendi illum.
                  Qui quo officia. Id sapiente in. Expedita est saepe.
                autor: Dean Franecki
                created_at: '2023-06-17T18:05:42.786Z'
                updated_at: '2023-06-17T18:05:42.786Z'
        '422':
          description: successful
          content:
            application/json:
              example:
                autor:
                - can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                texto:
                  type: string
                autor:
                  type: string
              required:
              - titulo
              - texto
              - autor
            examples:
              artigo:
                summary: create artigo
                value:
                  titulo: Cumque laboriosam ad. Labore id cumque. Minima quo quis.
                  texto: |-
                    Dolores harum consequuntur. Odio praesentium porro. Voluptatem maxime voluptates.
                    Dolorem ducimus id. Voluptas ea est. Non aut voluptas.
                  autor: Otha Herman
  "/artigos/{id}":
    parameters:
    - name: id
      in: path
      description: codigo de artigo
      required: true
      schema:
        type: integer
    get:
      summary: show artigo
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1
                titulo: Aut ipsam tenetur. Sapiente et dolor. Accusamus labore doloribus.
                texto: |-
                  Assumenda ut impedit. Perferendis voluptatibus veniam. Consequatur incidunt est.
                  Molestiae nihil nulla. Amet odit labore. Qui ut impedit.
                  Laboriosam soluta deleniti. Pariatur sed reprehenderit. Illo expedita voluptas.
                  Quia sunt quod. Et eum illo. Odio omnis rerum.
                autor: Kelle Hand
                created_at: '2023-06-17T18:05:42.799Z'
                updated_at: '2023-06-17T18:05:42.799Z'
    patch:
      summary: update artigo
      tags:
      - Artigos
      description: Updates Artigo
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                titulo: Est voluptatum minus. Est veniam et. Voluptatem et et.
                texto: |-
                  Veritatis in magni. Dicta iusto error. Nihil nemo iusto.
                  Perferendis voluptatem recusandae. Nemo et assumenda. Qui dolores earum.
                  Est dolores vitae. In atque odio. Perferendis blanditiis et.
                  Saepe libero reiciendis. Accusamus praesentium id. Dolores dignissimos dolore.
                autor: Gerry Luettgen
                id: 1
                created_at: '2023-06-17T18:05:42.806Z'
                updated_at: '2023-06-17T18:05:42.810Z'
    put:
      summary: update artigo
      tags:
      - Artigos
      description: Updates Artigo
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                titulo: Reprehenderit at et. Id earum odio. Voluptatum eaque sed.
                texto: |-
                  Sapiente rerum dolorum. Aperiam a voluptatem. Eos nulla mollitia.
                  Optio architecto labore. In quos inventore. Deserunt sed qui.
                autor: Darrick Zboncak
                id: 1
                created_at: '2023-06-17T18:05:42.816Z'
                updated_at: '2023-06-17T18:05:42.820Z'
    delete:
      summary: delete artigo
      tags:
      - Artigos
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1
                titulo: Libero accusamus ratione. Et quis eveniet. Aliquam exercitationem
                  dolore.
                texto: |-
                  Non aut vel. Eveniet consequatur id. Rerum ducimus eum.
                  In ipsam saepe. Vitae praesentium et. Consequatur delectus vitae.
                  Cumque molestias iure. Et eius eum. Ut voluptatem et.
                autor: Royal Feil VM
                created_at: '2023-06-17T18:05:42.824Z'
                updated_at: '2023-06-17T18:05:42.824Z'
  "/comentarios":
    get:
      summary: list comentarios
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
    post:
      summary: create comentario
      responses:
        '200':
          description: successful
  "/comentarios/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show comentario
      responses:
        '200':
          description: successful
    patch:
      summary: update comentario
      responses:
        '200':
          description: successful
    put:
      summary: update comentario
      responses:
        '200':
          description: successful
    delete:
      summary: delete comentario
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
